apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: mongo
  name: mongo-controller
spec:
  replicas: 1
  selector:
    matchLabels: # find below pods
      run: mongo
  template:
    metadata:
      labels:
        run: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          gcePersistentDisk:
            pdName: mongo-disk
            fsType: ext4
