apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    run: web
spec:
  type: LoadBalancer
  loadBalancerIP: "35.184.217.132"
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    run: web
